#!/usr/bin/env python3
"""SPIKE 3 Real-Device Verification Test Suite.

Connects to a real SPIKE Prime hub over USB and tests every Hub API method,
reporting which commands succeed, fail, or time out.

Run:
    python test_real_device.py [COM_PORT]
    python test_real_device.py          # auto-detect
    python test_real_device.py COM3     # explicit port

The test produces a verification table at the end with:
  ✅ VERIFIED  — command succeeded, result looks valid
  ⚠️ WARNING   — command ran but result is unexpected
  ❌ FAILED    — command raised an exception
  ⏭️ SKIPPED   — requires hardware not detected (e.g. no motor on port A)

Author: Auto-generated by audit process
"""

from __future__ import annotations
import sys, os, time, traceback

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import spike3
from spike3 import Hub
from spike3.enums import Color, Gesture, DeviceType, Orientation

# ── Result tracking ────────────────────────────────────────────────

class Result:
    VERIFIED = "✅ VERIFIED"
    WARNING  = "⚠️  WARNING"
    FAILED   = "❌ FAILED "
    SKIPPED  = "⏭️  SKIPPED"

results: list[dict] = []

def record(category: str, method: str, status: str, detail: str = ""):
    results.append({
        "category": category,
        "method": method,
        "status": status,
        "detail": detail[:120],
    })
    sym = {"VERIFIED": "✅", "WARNING": "⚠️", "FAILED": "❌", "SKIPPED": "⏭️"}
    s = sym.get(status.strip().split()[-1], "?")
    print(f"  {s} {method}: {detail[:90]}")


def safe_test(category: str, method: str, fn, validator=None):
    """Run fn(), record result. validator(result) -> (status, detail)."""
    try:
        result = fn()
        if validator:
            status, detail = validator(result)
        else:
            status = Result.VERIFIED
            detail = repr(result)[:120]
        record(category, method, status, detail)
        return result
    except TimeoutError as e:
        record(category, method, Result.FAILED, f"TIMEOUT: {e}")
    except Exception as e:
        record(category, method, Result.FAILED, f"{type(e).__name__}: {e}")
    return None


# ── Validators ─────────────────────────────────────────────────────

def v_info(r):
    if r and hasattr(r, 'fw_major'):
        return Result.VERIFIED, f"FW {r.fw_major}.{r.fw_minor}.{r.fw_build}, RPC {r.rpc_major}.{r.rpc_minor}.{r.rpc_build}"
    return Result.WARNING, repr(r)

def v_string(r):
    if isinstance(r, str) and len(r) > 0:
        return Result.VERIFIED, repr(r)
    return Result.WARNING, f"empty or not string: {repr(r)}"

def v_int(r):
    if isinstance(r, int):
        return Result.VERIFIED, str(r)
    return Result.WARNING, f"not int: {repr(r)}"

def v_int_range(lo, hi):
    def v(r):
        if isinstance(r, (int, float)) and lo <= r <= hi:
            return Result.VERIFIED, str(r)
        if isinstance(r, (int, float)):
            return Result.WARNING, f"{r} outside [{lo},{hi}]"
        return Result.FAILED, f"not numeric: {repr(r)}"
    return v

def v_bool(r):
    if isinstance(r, bool):
        return Result.VERIFIED, str(r)
    return Result.WARNING, f"not bool: {repr(r)}"

def v_eval(r):
    if isinstance(r, str) and r.strip():
        return Result.VERIFIED, repr(r)
    if isinstance(r, str) and r == "":
        return Result.WARNING, "empty response (timeout or no REPL?)"
    return Result.FAILED, f"unexpected: {repr(r)}"

def v_any_ok(r):
    return Result.VERIFIED, repr(r)[:100]

def v_list(r):
    if isinstance(r, list):
        return Result.VERIFIED, f"{len(r)} items: {repr(r)[:80]}"
    return Result.WARNING, repr(r)

def v_dict(r):
    if isinstance(r, dict):
        return Result.VERIFIED, f"{len(r)} entries: {repr(r)[:80]}"
    return Result.WARNING, repr(r)

def v_none_ok(r):
    return Result.VERIFIED, "OK (no exception)"

def v_fire_forget(r):
    return Result.VERIFIED, "sent (fire-and-forget)"


# ── Main test ──────────────────────────────────────────────────────

def main():
    # ── Connect ────────────────────────────────────────────────────
    port = sys.argv[1] if len(sys.argv) > 1 else None
    hub = None

    print("=" * 70)
    print("SPIKE 3 REAL-DEVICE VERIFICATION TEST")
    print("=" * 70)

    if port:
        print(f"\nConnecting to {port}...")
        try:
            hub = Hub.connect_usb(port)
        except Exception as e:
            print(f"❌ Cannot connect to {port}: {e}")
            sys.exit(1)
    else:
        print("\nAuto-detecting hub...")
        hubs = Hub.find_hubs()
        if not hubs:
            print("❌ No SPIKE 3 hubs found. Connect a hub and try again.")
            sys.exit(1)
        print(f"Found: {hubs[0]}")
        try:
            hub = Hub.connect_usb(hubs[0]["port"])
        except Exception as e:
            print(f"❌ Cannot connect: {e}")
            sys.exit(1)

    print(f"✅ Connected.\n")
    time.sleep(0.3)

    # ── Category 1: Atlantis Protocol Commands ─────────────────────
    cat = "1-ATLANTIS"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Atlantis protocol commands (binary msg_id based)")
    print(f"{'─'*60}")

    safe_test(cat, "get_info()", lambda: hub.get_info(timeout=3), v_info)

    safe_test(cat, "get_hub_name()", lambda: hub.get_hub_name(timeout=3), v_string)

    safe_test(cat, "get_device_uuid()", lambda: hub.get_device_uuid(timeout=3), v_string)

    safe_test(cat, "set_notification_interval(50)",
              lambda: hub.set_notification_interval(50, timeout=3), v_any_ok)

    time.sleep(0.5)

    # ── Category 2: Notification Polling ────────────────────────────
    cat = "2-NOTIF"
    print(f"\n{'─'*60}")
    print(f"[{cat}] DeviceNotification polling (passive sensor data)")
    print(f"{'─'*60}")

    safe_test(cat, "poll(0.5)", lambda: hub.poll(timeout=0.5), v_any_ok)

    safe_test(cat, "get_battery()",
              lambda: hub.get_battery(),
              v_int_range(-1, 100))

    safe_test(cat, "get_imu()",
              lambda: hub.get_imu(),
              lambda r: (Result.VERIFIED, repr(r)[:80]) if r else (Result.WARNING, "None (no notif yet?)"))

    safe_test(cat, "get_matrix()",
              lambda: hub.get_matrix(),
              lambda r: (Result.VERIFIED, repr(r)[:60]) if r else (Result.VERIFIED, "None (normal if no LED data)"))

    safe_test(cat, "get_all_motors()",
              lambda: hub.get_all_motors(),
              v_dict)

    safe_test(cat, "get_port_info()",
              lambda: hub.get_port_info(),
              v_dict)

    # Detect what's connected for later tests
    motors = hub.get_all_motors()
    motor_port = next(iter(motors.keys()), None) if motors else None
    port_info = hub.get_port_info()

    # Find sensor ports
    color_port = None
    distance_port = None
    force_port = None
    for p, did in port_info.items():
        if did == 61:
            color_port = p
        elif did == 62:
            distance_port = p
        elif did == 63:
            force_port = p

    print(f"\n  Detected: motor={motor_port}, color={color_port}, "
          f"distance={distance_port}, force={force_port}")

    # ── Category 3: eval_python Core ────────────────────────────────
    cat = "3-EVAL"
    print(f"\n{'─'*60}")
    print(f"[{cat}] eval_python() — MicroPython REPL basic")
    print(f"{'─'*60}")

    safe_test(cat, "eval_python('1+1')",
              lambda: hub.eval_python("1+1"),
              lambda r: (Result.VERIFIED, f"got '{r}'") if r.strip() == "2" else
                        (Result.WARNING, f"expected '2', got '{r}'"))

    safe_test(cat, "eval_python('import hub;hub.info()')",
              lambda: hub.eval_python("import hub;hub.info()"),
              v_eval)

    # ── Category 4: Sensor APIs via eval_python ────────────────────
    cat = "4-SENSOR"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Sensor APIs via eval_python (JS-verified ✓ and unverified)")
    print(f"{'─'*60}")

    # Color sensor
    if color_port is not None:
        safe_test(cat, f"color(port={color_port}) [JS ✓]",
                  lambda: hub.color(color_port),
                  v_int_range(-1, 10))
        safe_test(cat, f"reflection(port={color_port}) [JS ✓]",
                  lambda: hub.reflection(color_port),
                  v_int_range(0, 100))
        safe_test(cat, f"ambient(port={color_port}) [JS ⚠ NOT FOUND]",
                  lambda: hub.ambient(color_port),
                  v_int_range(0, 100))
        safe_test(cat, f"raw_rgb(port={color_port}) [JS ⚠ uses rgbi()]",
                  lambda: hub.raw_rgb(color_port),
                  lambda r: (Result.VERIFIED, repr(r)) if isinstance(r, tuple) and len(r) == 3 else
                            (Result.WARNING, repr(r)))
    else:
        record(cat, "color() [JS ✓]", Result.SKIPPED, "no color sensor detected")
        record(cat, "reflection() [JS ✓]", Result.SKIPPED, "no color sensor")
        record(cat, "ambient() [JS ⚠]", Result.SKIPPED, "no color sensor")
        record(cat, "raw_rgb() [JS ⚠]", Result.SKIPPED, "no color sensor")

    # Distance sensor
    if distance_port is not None:
        safe_test(cat, f"distance(port={distance_port}) [JS ✓]",
                  lambda: hub.distance(distance_port),
                  v_int_range(-1, 2500))
    else:
        record(cat, "distance() [JS ✓]", Result.SKIPPED, "no distance sensor detected")

    # Force sensor
    if force_port is not None:
        safe_test(cat, f"force(port={force_port}) [JS ✓]",
                  lambda: hub.force(force_port),
                  lambda r: (Result.VERIFIED, f"{r} N") if isinstance(r, (int, float)) and 0 <= r <= 10 else
                            (Result.WARNING, repr(r)))
        safe_test(cat, f"is_pressed(port={force_port}) [JS ✓]",
                  lambda: hub.is_pressed(force_port),
                  v_bool)
    else:
        record(cat, "force() [JS ✓]", Result.SKIPPED, "no force sensor detected")
        record(cat, "is_pressed() [JS ✓]", Result.SKIPPED, "no force sensor")

    # Motor sensor queries
    if motor_port is not None:
        safe_test(cat, f"motor_position(port={motor_port}) [JS ⚠ relative_position?]",
                  lambda: hub.motor_position(motor_port),
                  v_int)
        safe_test(cat, f"motor_speed(port={motor_port}) [JS ⚠ velocity?]",
                  lambda: hub.motor_speed(motor_port),
                  v_int)
        safe_test(cat, f"motor_is_stalled(port={motor_port}) [JS ⚠ NOT FOUND]",
                  lambda: hub.motor_is_stalled(motor_port),
                  v_bool)
        safe_test(cat, f"motor_was_interrupted(port={motor_port}) [JS ⚠ NOT FOUND]",
                  lambda: hub.motor_was_interrupted(motor_port),
                  v_bool)
    else:
        record(cat, "motor_position() [JS ⚠]", Result.SKIPPED, "no motor detected")
        record(cat, "motor_speed() [JS ⚠]", Result.SKIPPED, "no motor detected")
        record(cat, "motor_is_stalled() [JS ⚠]", Result.SKIPPED, "no motor detected")
        record(cat, "motor_was_interrupted() [JS ⚠]", Result.SKIPPED, "no motor detected")

    # ── Category 5: Hub Sensor APIs ────────────────────────────────
    cat = "5-HUB-SENSORS"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Hub built-in sensors via eval_python")
    print(f"{'─'*60}")

    safe_test(cat, "left_button_pressed() [JS ⚠ hub.button.pressed?]",
              lambda: hub.left_button_pressed(),
              v_bool)

    safe_test(cat, "right_button_pressed() [JS ⚠ hub.button.pressed?]",
              lambda: hub.right_button_pressed(),
              v_bool)

    safe_test(cat, "left_button_was_pressed() [JS ⚠ NOT FOUND]",
              lambda: hub.left_button_was_pressed(),
              v_bool)

    safe_test(cat, "right_button_was_pressed() [JS ⚠ NOT FOUND]",
              lambda: hub.right_button_was_pressed(),
              v_bool)

    safe_test(cat, "get_gesture() [JS ✓ motion_sensor.gesture]",
              lambda: hub.get_gesture(),
              v_int_range(-1, 4))

    safe_test(cat, "was_gesture(3) [JS ⚠ NOT FOUND]",
              lambda: hub.was_gesture(3),
              v_bool)

    safe_test(cat, "temperature() [JS ⚠ NOT FOUND]",
              lambda: hub.temperature(),
              v_int_range(10, 60))

    safe_test(cat, "charger_connected() [JS ⚠ charger_detect?]",
              lambda: hub.charger_connected(),
              v_bool)

    # ── Category 6: Tunnel commands (fire-and-forget) ──────────────
    cat = "6-TUNNEL"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Tunnel commands via ConsoleNotification (fire-and-forget)")
    print(f"{'─'*60}")

    safe_test(cat, "display_clear() [JS ✓]",
              lambda: hub.display_clear(),
              v_fire_forget)

    safe_test(cat, "display_text('Hi') [JS ✓]",
              lambda: hub.display_text("Hi"),
              v_fire_forget)

    time.sleep(1.5)

    safe_test(cat, "display_image('9909999099...') [JS ✓]",
              lambda: hub.display_image("9909999099000990099009900"),
              v_fire_forget)

    time.sleep(1)

    safe_test(cat, "display_set_pixel(2,2,100) [JS ✓]",
              lambda: (hub.display_clear(), time.sleep(0.3),
                       hub.display_set_pixel(2, 2, 100))[-1],
              v_fire_forget)

    time.sleep(0.5)

    safe_test(cat, "display_number(42) [JS ⚠ NOT RPC]",
              lambda: hub.display_number(42),
              v_fire_forget)

    time.sleep(1)
    safe_test(cat, "display_clear()", lambda: hub.display_clear(), v_fire_forget)

    safe_test(cat, "sound_beep(100, 60) [JS ✓]",
              lambda: hub.sound_beep(100, 60),
              v_fire_forget)

    time.sleep(0.5)

    safe_test(cat, "sound_beep_for(80, 69, 500) [JS ✓]",
              lambda: hub.sound_beep_for(80, 69, 500),
              v_fire_forget)

    time.sleep(0.6)

    safe_test(cat, "sound_play_note(72, 300) [JS ~✓ beep_for_time]",
              lambda: hub.sound_play_note(72, 300),
              v_fire_forget)

    time.sleep(0.4)

    safe_test(cat, "sound_off() [JS ✓]",
              lambda: hub.sound_off(),
              v_fire_forget)

    # hub light
    safe_test(cat, "hub_light_on(9=RED) [JS ✓ center_button_lights]",
              lambda: hub.send_tunnel(spike3.tunnel.hub_light_on(9)),
              v_fire_forget)
    time.sleep(0.5)
    safe_test(cat, "hub_light_off() [JS ⚠ NOT RPC]",
              lambda: hub.send_tunnel(spike3.tunnel.hub_light_off()),
              v_fire_forget)

    # reset_yaw
    safe_test(cat, "reset_yaw() [JS ✓]",
              lambda: hub.send_tunnel(spike3.tunnel.reset_yaw()),
              v_fire_forget)

    # ── Category 7: Motor commands ─────────────────────────────────
    cat = "7-MOTOR"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Motor tunnel commands")
    print(f"{'─'*60}")

    if motor_port is not None:
        safe_test(cat, f"motor_start(port={motor_port}, speed=30) [JS ✓]",
                  lambda: hub.motor_start(motor_port, 30),
                  v_fire_forget)
        time.sleep(1)

        safe_test(cat, f"motor_stop(port={motor_port}) [JS ✓]",
                  lambda: hub.motor_stop(motor_port),
                  v_fire_forget)
        time.sleep(0.3)

        safe_test(cat, f"motor_run_degrees(port={motor_port}, 20, 90) [JS ✓]",
                  lambda: hub.motor_run_degrees(motor_port, 20, 90),
                  v_fire_forget)
        time.sleep(1.5)

        safe_test(cat, f"motor_run_timed(port={motor_port}, 20, 500) [JS ✓]",
                  lambda: hub.motor_run_timed(motor_port, 20, 500),
                  v_fire_forget)
        time.sleep(1)

        safe_test(cat, f"motor_go_to_position(port={motor_port}, 20, 0) [JS ⚠ abs vs rel]",
                  lambda: hub.motor_go_to_position(motor_port, 20, 0),
                  v_fire_forget)
        time.sleep(1.5)

        safe_test(cat, f"motor_set_position(port={motor_port}, 0) [JS ✓]",
                  lambda: hub.motor_set_position(motor_port, 0),
                  v_fire_forget)
        time.sleep(0.3)
    else:
        for cmd in ["motor_start", "motor_stop", "motor_run_degrees",
                     "motor_run_timed", "motor_go_to_position", "motor_set_position"]:
            record(cat, cmd, Result.SKIPPED, "no motor detected")

    # ── Category 8: File system ────────────────────────────────────
    cat = "8-FS"
    print(f"\n{'─'*60}")
    print(f"[{cat}] File system commands (Atlantis)")
    print(f"{'─'*60}")

    safe_test(cat, "list_files('', slot=0) [JS ✓]",
              lambda: hub.list_files("", slot=0),
              v_list)

    safe_test(cat, "list_path('', slot=0) [JS ✓]",
              lambda: hub.list_path("", slot=0),
              v_any_ok)

    # ── Category 9: Program flow ───────────────────────────────────
    cat = "9-PROGRAM"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Program flow commands")
    print(f"{'─'*60}")

    safe_test(cat, "start_program(slot=0) [JS ✓]",
              lambda: hub.start_program(0, timeout=3),
              v_any_ok)

    time.sleep(1)

    safe_test(cat, "stop_program(slot=0) [JS ✓]",
              lambda: hub.stop_program(0, timeout=3),
              v_any_ok)

    # ── Category 10: Additional MicroPython APIs (alternatives) ────
    cat = "10-ALT-API"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Alternative MicroPython API names (from JS)")
    print(f"{'─'*60}")

    # Test both our names and JS names to see which works
    if motor_port is not None:
        pname = chr(65 + motor_port)

        safe_test(cat, f"motor.relative_position(port.{pname}) [JS name]",
                  lambda: hub.eval_python(f"motor.relative_position(port.{pname})"),
                  v_eval)

        safe_test(cat, f"motor.absolute_position(port.{pname}) [JS name]",
                  lambda: hub.eval_python(f"motor.absolute_position(port.{pname})"),
                  v_eval)

        safe_test(cat, f"motor.get_position(port.{pname}) [our name]",
                  lambda: hub.eval_python(f"motor.get_position(port.{pname})"),
                  v_eval)

        safe_test(cat, f"motor.velocity(port.{pname}) [JS name]",
                  lambda: hub.eval_python(f"motor.velocity(port.{pname})"),
                  v_eval)

        safe_test(cat, f"motor.get_speed(port.{pname}) [our name]",
                  lambda: hub.eval_python(f"motor.get_speed(port.{pname})"),
                  v_eval)

        safe_test(cat, f"motor.get_duty_cycle(port.{pname}) [JS name]",
                  lambda: hub.eval_python(f"motor.get_duty_cycle(port.{pname})"),
                  v_eval)
    else:
        record(cat, "motor alt API names", Result.SKIPPED, "no motor")

    # Test hub sensor alternative names
    safe_test(cat, "hub.motion_sensor.tilt_angles() [JS name]",
              lambda: hub.eval_python("hub.motion_sensor.tilt_angles()"),
              v_eval)

    safe_test(cat, "hub.motion_sensor.acceleration() [JS name]",
              lambda: hub.eval_python("hub.motion_sensor.acceleration()"),
              v_eval)

    safe_test(cat, "hub.motion_sensor.angular_velocity() [JS name]",
              lambda: hub.eval_python("hub.motion_sensor.angular_velocity()"),
              v_eval)

    safe_test(cat, "hub.motion_sensor.up_face() [JS name]",
              lambda: hub.eval_python("hub.motion_sensor.up_face()"),
              v_eval)

    safe_test(cat, "hub.motion_sensor.get_gesture() [our name]",
              lambda: hub.eval_python("hub.motion_sensor.get_gesture()"),
              v_eval)

    safe_test(cat, "hub.motion_sensor.gesture() [JS name]",
              lambda: hub.eval_python("hub.motion_sensor.gesture()"),
              v_eval)

    # Button API variants
    safe_test(cat, "hub.left_button.is_pressed() [our name]",
              lambda: hub.eval_python("hub.left_button.is_pressed()"),
              v_eval)

    safe_test(cat, "hub.button.left.is_pressed() [alt name]",
              lambda: hub.eval_python("hub.button.left.is_pressed()"),
              v_eval)

    # Temperature
    safe_test(cat, "hub.temperature() [our name]",
              lambda: hub.eval_python("hub.temperature()"),
              v_eval)

    # Battery
    safe_test(cat, "hub.battery.charger_connected() [our name]",
              lambda: hub.eval_python("hub.battery.charger_connected()"),
              v_eval)

    safe_test(cat, "battery.charger_detect() [JS name]",
              lambda: hub.eval_python("battery.charger_detect()"),
              v_eval)

    # Color sensor rgbi vs separate getters
    if color_port is not None:
        pname = chr(65 + color_port)
        safe_test(cat, f"color_sensor.rgbi(port.{pname}) [JS name]",
                  lambda: hub.eval_python(f"color_sensor.rgbi(port.{pname})"),
                  v_eval)
        safe_test(cat, f"color_sensor.get_red(port.{pname}) [our name]",
                  lambda: hub.eval_python(f"color_sensor.get_red(port.{pname})"),
                  v_eval)

    # ── Category 11: Ultrasonic LEDs / Color matrix ────────────────
    cat = "11-EXTRAS"
    print(f"\n{'─'*60}")
    print(f"[{cat}] Extra commands (ultrasonic LEDs, color matrix)")
    print(f"{'─'*60}")

    if distance_port is not None:
        safe_test(cat, f"ultrasonic_light_up(port={distance_port}) [JS ✓]",
                  lambda: hub.send_tunnel(
                      spike3.tunnel.ultrasonic_light_up(distance_port, [100, 0, 100, 0])),
                  v_fire_forget)
        time.sleep(0.5)
        safe_test(cat, "ultrasonic_light_off",
                  lambda: hub.send_tunnel(
                      spike3.tunnel.ultrasonic_light_up(distance_port, [0, 0, 0, 0])),
                  v_fire_forget)
    else:
        record(cat, "ultrasonic_light_up()", Result.SKIPPED, "no distance sensor")

    # ── Cleanup ────────────────────────────────────────────────────
    print(f"\n{'─'*60}")
    print("[CLEANUP]")
    print(f"{'─'*60}")
    try:
        hub.display_clear()
        hub.sound_off()
        time.sleep(0.3)
    except Exception:
        pass
    hub.close()
    print("  Hub disconnected.\n")

    # ── Print summary table ────────────────────────────────────────
    print("=" * 70)
    print("VERIFICATION SUMMARY TABLE")
    print("=" * 70)
    print(f"{'Category':<16} {'Method':<45} {'Status':<12}")
    print("-" * 70)

    counts = {"VERIFIED": 0, "WARNING": 0, "FAILED": 0, "SKIPPED": 0}
    for r in results:
        s = r["status"].split()[-1]
        counts[s] = counts.get(s, 0) + 1
        # Truncate method name for table
        meth = r["method"][:44]
        cat = r["category"][:15]
        print(f"{cat:<16} {meth:<45} {r['status']}")

    print("-" * 70)
    total = len(results)
    print(f"\nTotal: {total}  |  "
          f"✅ {counts['VERIFIED']} verified  |  "
          f"⚠️  {counts['WARNING']} warnings  |  "
          f"❌ {counts['FAILED']} failed  |  "
          f"⏭️  {counts['SKIPPED']} skipped")

    # Print details for failures and warnings
    fails_and_warns = [r for r in results if "FAILED" in r["status"] or "WARNING" in r["status"]]
    if fails_and_warns:
        print(f"\n{'─'*70}")
        print("DETAILS FOR FAILURES AND WARNINGS")
        print(f"{'─'*70}")
        for r in fails_and_warns:
            print(f"  {r['status']}  {r['method']}")
            print(f"           → {r['detail']}")

    # Print JS verification tags
    print(f"\n{'─'*70}")
    print("JS VERIFICATION LEGEND")
    print(f"{'─'*70}")
    print("  [JS ✓]     = Exact match in deobfuscated JS source")
    print("  [JS ⚠ ...]  = Different name or not found in JS")
    print("  [JS ~✓]    = Close match / alias in JS")
    print("  (no tag)   = Not directly comparable to JS")

    # Return exit code
    if counts["FAILED"] > 0:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
